name: Проверка компиляции

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Компиляция
      shell: cmd
      run: |
        git fetch origin main
        
        for /f "delims=" %%f in ('git diff --name-only origin/main...HEAD ^| findstr "\.cpp$"') do (
          echo.
          echo Компилирую: %%f
          cl /EHsc /nologo /Fe:temp_test.exe %%f
          if errorlevel 1 (
            echo ОШИБКА в %%f
            exit /b 1
          )
          echo OK: %%f
        )
        
        echo.
        echo Все файлы скомпилированы